name: Transcriber
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment: productions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: remove previous client container
        run: |
          docker stop transcriber-client || true
          docker rm transcriber-client || true
          docker image remove transcriber-client:latest || true

      - name: Build and push Docker images for client
        run: |
          docker build -t transcriber-client:latest ./client --no-cache

      - name: Deploy Docker container for client
        run: |
          docker run -d --name transcriber-client -p 3040:3000 transcriber-client:latest

      - name: Create .env file for server
        run: |
          rm ./server/.env || true
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> ./server/.env

      - name: remove previous server container
        run: |
          docker stop transcriber-server || true
          docker rm transcriber-server || true
          docker image remove transcriber-server:latest || true

      - name: Build and push Docker images for server
        run: |
          docker build -t transcriber-server:latest ./server --no-cache

      - name: Deploy Docker container for server
        run: |
          docker run -d --name transcriber-server -p 5049:5000 transcriber-server:latest
